### ISSUE TITLE
Add testing framework to compass project and make it runnable

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#13]
**Description**

Add testing framework to compass project.

**Reasons**

Allow to execute integration test againts k8s cluster.

**AC**
- [x] tests directory where we have all integration tests for all compass components #20
- [x] release pipeline for tests image [#1084](https://github.com/kyma-project/test-infra/pull/1084)
- [x] octopus used as a testing framework #23
- [x] add a document how to run compass #23
  - [x] run on Kyma latest released version with minimal required modules in, eg. essential-data, test-runner, istio #23
  - [x] investigate if we can use kymaCLI, or even kymaCLI utils, if not we have only minikube.sh script with all others from Kyma #23
- [x] update main Readme with how to run and test compass points to detailed documents in /docs #23
