### ISSUE TITLE
Setup repository, create components structure and and provide APIs

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#2]
**AC**
- [x] apply https://github.com/kyma-project/community/tree/master/guidelines/internal-guidelines/repository-template into compass repository - @kfurgol #5
- [x] Github repo setup - @kfurgol 
  - [x] Enabled required reviews for pull requests (at least one review)
  - [x] License check required
  - [x] Set up labels 
  - [x] Add compass to prow config [#1009](https://github.com/kyma-project/test-infra/pull/1009)
- [x] create project structure, define and add proper components catalogs - @kfurgol #6
- [x] add release pipelines per component - @tgorgol kyma-project/test-infra#1011
- [x] add helm charts for the components - @kfurgol #10 
- [x] investigate file upload with graphql - @kfurgol #11 
- [x] define API per components and place specification under /component/api directory
- [x] all stakeholders can do a review of those APIs

**Comment by crabtree** [comment]
Suggested API reviewers @lszymik, @a-thaler, @akrausesap, @akgalwas

**Comment by a-thaler** [comment]
You should decide on how people can access the API definition. Is it part of rendered documentation, or part of source code or maybe it is just served at runtime by the service. I always prefer the runtime approach as it will always fit to the reality.
