### ISSUE TITLE
APIs mock implementation

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#3]
**AC**
- [ ] ~~create list of test-cases showing full flow, implement main ones (when test-cases ready ask for review @PK85 )~~
- [ ] provide interfaces for APIs defined in #2  and provide mock implementation in gateway component
- [ ] store data in-memory database
- [ ] interfaces needs to be already nicely defined that will help us in next issues to replace mock with production implementation
