### ISSUE TITLE
Provisioner end-to-end test on Gardener

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/compass#446]
**Description**

Currently, the Provisioner end-to-end test is provisioning cluster only on GKE. There is a need to have a similar automated test using Gardener (preferably with Azure provider) as the underlying infrastructure.

**The test library should be reusable since we want to provide more test cases.**

**Acceptance:**
- [x] Gardener project configured
- [ ] Tests adjusted to support both providers
- [x] New pipeline created or the existing one adjusted
- [x] Provisioner tests written in a 'library' manner

**Subtasks**
- [x] Investigate and fix failing test - @rafalpotempa @franpog859

**Comment by franpog859** [comment]
Correct me if I'm wrong, but the tests should use only Gardener provider for now in my opinion. I think we can delete the `[ ] Tests adjusted to support both providers` acceptance criterium
