### ISSUE TITLE
Create compatibility layer for REST Connectors to work seamlessly with Compass

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#620]
**Description**
Compass must work with REST Connectors (e.g. Wordpress Application). Take into account all findings from our [Investigation](https://github.com/kyma-incubator/compass/pull/612).

**Reasons**

We'd like to give more time for all existing REST connectors to be reimplemented to use new GraphQL APIs.

**AC**
- implement Application Connector and Applications Registry REST APIs in Compass and make sure they work e2e from External Application point of view.
- run existing integration test for REST API and ensure that everything works as expected
- test REST APIs with varkes
- test with existing commerce instance
- mark REST APIs as deprecated

**Related tickets**
- [Support Application Connector service REST API in the API-gateway](https://github.com/kyma-incubator/compass/issues/18)
- [Support Metadata service REST API in the API-gateway](https://github.com/kyma-project/kyma/issues/4240)

**Comment by aszecowka** [comment]
Proposal for tasks split:
- [ ] Scaffold project structure
  - [ ] create Go project in /components/compatibility-layer with Makefile, Dockerfile, consider using go modules
  - [ ] create Go project in /tests/comatibility-layer-tests
  - [ ] helm chart
  - [ ] configure Prow Jobs
- [ ] PoC about propagating credentials. There is a call to REST Adapter with client certs, how to propagate client identity to do director and connector graphql endpoints? @crabtree **IN PROGRESS**
- [ ] Implement Application Registry API] https://kyma-project.io/docs/1.8/components/application-connector/specifications/metadataapi/
  For not supported cases (for example, lack of API Packages, FetchRequests) we should return an error.
- [ ] Implement connector API  https://kyma-project.io/docs/1.8/components/application-connector/specifications/connectorapi/
