### ISSUE TITLE
Runtime upgrades with Compass Provisioner

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#647]
**Description**

The goal of this task is to have the first (simplest) version of mutation that allows the user to upgrade his Kyma Runtime to the newer version.

The current assumptions are:
- no additional migration actions are needed (they will be handled manually)
- upgrade increases Kyma version by one release (no automated subsequent upgrades in cases such as 1.5 -> 1.9 upgrade)

**Acceptance Criteria**
- first version of API designed and implemented
- short tutorial with commands and exemplary calls created 
- prepare and implement a pipeline for testing runtime upgrades

**Subtasks**
- [x] Do research and prepare a plan for implementation, discuss with the team - @Szymongib 
- [x] Upgrade in Installation SDK - @Maladie 
- [x] Prepare API, change Provisioner
- [x] Create a tutorial / guide / docs - @majakurcius 
- [x] Implement tests 

Follow up issue for pipelines integration: https://github.com/kyma-project/kyma/issues/8080
