### ISSUE TITLE
Provisioning of custom components

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#942]
**Description**

In current state, Provisioner accepts ComponentConfigurationInput of following model:
```
&gqlschema.ComponentConfigurationInput{ 
 			Component: component.Name, 
 			Namespace: component.Namespace, 
}
```

With the recent addition to Kyma Installer, there is now a possibility to define the URL Source of a component to be installed. We would like to introduce this functionality in Provisioner, this would require changing the input model to the following structure:
```
&gqlschema.ComponentConfigurationInput{ 
 			Component: component.Name, 
 			Namespace: component.Namespace, 
 			Source:
 			  URL: component.Source.URL,
}
```

**Acceptance Criteria**
- Provisioner accepts URL Source as a parameter for Component Configuration
- URL Sources are propagated to KymaInstallation CR in a provisioned cluster

**Subtasks**
- [x] Provisioner schema changed
- [x] Database schema updated
- [x] Input for documentation provided
- [ ] Documentation updated
