### ISSUE TITLE
On demand revision of Kyma installed on provisioned clusters

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#976]
**Description**

We would like to allow a client to specify an exact revision of Kyma they would like to have installed on a provisioned cluster. This can help with debugging/tracking/fixing issues both during development and on already live environments.

There is already an implementation that was used internally by the dev team, the best idea would be to productize that: https://github.com/kyma-incubator/compass/pull/916

**Acceptance Criteria**
- It is possible to specify exact Kyma revision in provisioner
- Charts/artifacts of the chosen revision are fetched and Kyma is installed on a cluster

**Subtasks**
- [ ] Fetch releases only when request is received
- [x] Create tests for the implementation
- [x] Extract SQL-related functionalities into a new package
